server {
    listen 8080;
    session on;
    server_name localhost;
    host 127.0.0.1;
    root www/site1;
    client_max_body_size 1M;
    index index.html;
    error_page 404 errors/404.html;

    location / {
        allow_methods GET;
        autoindex off;
    }

    location /cgi {
        allow_methods GET POST PUT DELETE;
        alias cgi-bin;
        cgi on;
        upload_path www/site1/uploads;
    }

    location /uploads {
        root www/site1/uploads;
        allow_methods GET POST PUT DELETE;
        autoindex on;
        upload_path www/site1/uploads;
    }
}
