server {
    listen 8080;
    server_name localhost;
    host 127.0.0.1;
    root www/site1;
    client_max_body_size 3000000;
    index index.html;
    error_page 404 /errors/404.html;

    location / {
        allow_methods GET;
        autoindex off;
    }
}

server {
    listen 8080;
    server_name nexthost.com;
    host 127.0.0.1;
    root www/site2;
    client_max_body_size 3000000;
    index index.html;
    error_page 404 /errors/404.html;

    location / {
        allow_methods GET;
        autoindex off;
    }
}
