server {
    listen 8080;
    server_name localhost;
    root /home/antoine/webser_06/www/site1;  # or your webserv_tester/www
    cgi-bin test/cgi-bin;

    location / {
        allow_methods GET;
        index index.html;

        cgi_ext .bla;
        cgi bla cgi_test;   # use 'cgi', not 'cgi_path'
    }

    location /post_body {
        allow_methods POST;
        client_max_body_size 100;
    }

    location /directory/ {
        allow_methods GET;
        root /home/antoine/webser_06/YoupiBanane;
        index youpi.bad_extension;
        autoindex off;
        cgi_ext .bla;
        cgi bla cgi_test;
    }
}
